### ISSUE TITLE
Make exercise template parser consistent with TMC-server

### ISSUE THREAD

**Issue by ljleppan** [testmycode/tmc-langs#25]
Currently the [ExerciseBuilder](https://github.com/testmycode/tmc-langs/blob/master/tmc-langs-framework/src/main/java/fi/helsinki/cs/tmc/langs/domain/ExerciseBuilder.java) looks for a set of hard coded strings within the exercise and uses them to parse the project stub and the model solution.

This is not consistent with the way the current TMC-Server implementation parses this metadata from the exercise template and breaks backwards compability with C projects.

To fix this, we need to replicate the TMC-Servers parsing logic from [LineCommentBasedFilter](https://github.com/testmycode/tmc-server/blob/master/lib/course_refresher/line_comment_based_filter.rb) and [BlockCommentBasedFilter](https://github.com/testmycode/tmc-server/blob/master/lib/course_refresher/block_comment_based_filter.rb) so that Java uses the line comment style and Make uses the block comment style.

**Comment by DarthKipsu** [comment]
I'll work on this.

Any extra info on what should I consider regarding this line "...Java uses the line comment style and Make uses the block comment style"?

**Comment by jamox** [comment]
Not sure what was meant by that, this seems to be just a stepping stone to correct/ideal implementation.
