### ISSUE TITLE
Language aware exercise template parser

### ISSUE THREAD

**Issue by ljleppan** [testmycode/tmc-langs#26]
**This issue depends on #25.**

In an ideal case, we would like to allow any style of comments legal in a language's syntax to be used to mark the stub and solution blocks in exercise templates.

For this to be possible, the language plugins must supply the template parser with information on what kind of comment strings to except. So for Java, accept comments of type `// ..` and `/* .. */`, and for python accept comments of type `# ..` and `"""\n .. \n"""`.

The parser should be adapted to retrieve information of possible `start` and `end` symbols from a language plugin and then parse the exercise template based on those.

**Comment by DarthKipsu** [comment]
Where in language plugin should this information be provided in? I can work on this, but I'd like to get some more info on what is required on the plugins side.

**Comment by ljleppan** [comment]
I suspect the most preferable way to implement this is by building all the logic in `tmc-langs-framework` and then only have the comment tokens / regexes / whatevers in the specific plugins. Actual implementation details are left to the coder.
