### ISSUE TITLE
Copying empty files at stub generation

### ISSUE THREAD

**Issue by baobabKoodaa** [testmycode/tmc-langs#59]
When producing a stub, Filer doesn't...
...copy empty files (documented in source code)
...copy folders, unless the folder/its subfolders contain non empty files (not documented)

Is this functionality desired? If it serves a purpose, then maybe keep it this way. We just noticed that one of our assignments in the Introduction to Algorithms course broke with the latest TMC update. Many students spent time wondering why their perfectly working code isn't passing local tests. The assignment is about reading file names in sub directories recursively. We fixed our project by inserting something into all the empty files used in testing and it works for us now.

**Comment by jamox** [comment]
Empty folders are and should be ignored (just like git)
Behaviour for empty files, however, changed, and is now more like what it was earlier.

**Comment by jamox** [comment]
Fixed by 9d63cd51a817f4addae297dd6c2c707d5806aa1c
